### ISSUE TITLE
bugfix: "access control" vs "assess control"

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/ocdb#11]
![image](https://user-images.githubusercontent.com/5713754/68634834-af566f80-04c4-11ea-93eb-21626ae9e8de.png)

Should be "``AC: Access Control``"

**Comment by shawndwells** [comment]
Also, s/Personnell Security/Personnel Security/r

![image](https://user-images.githubusercontent.com/5713754/68634872-d0b75b80-04c4-11ea-9046-df8446176fc4.png)

**Comment by isimluk** [comment]
Sorry about that.

Interestingly, my emacs does not highlight typos in Typescript source files. That's weird.
