### ISSUE TITLE
Detailed Navigation for each open control

### ISSUE THREAD

**Issue by isimluk** [RedHatGov/ocdb#12]
Like there is on the old site.

![scrot](https://user-images.githubusercontent.com/6666052/69057814-5a59b280-0a0a-11ea-972d-979de2a4deaa.jpg)

**Comment by shawndwells** [comment]
Another option,  or at least an incremental step, could be to create subnav by NIST control family.

e.g

CoreOS 4.x
* Access Control
* Configuration Management
* etc

**Comment by isimluk** [comment]
We can simply add the control families to the menu. However, it would be duplicate to the toolbar filtering based on control families. The duplication of control elements feels unprofessional. I will experiment for a while, hopefully I can come up with something.

**Comment by isimluk** [comment]
![x](https://user-images.githubusercontent.com/6666052/70628250-bdacbe00-1c1f-11ea-8322-573e7c0973e1.jpg)

Ha. Done!
