### ISSUE TITLE
RFE: Color code "status" column

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/ocdb#6]
Existing ATO Pathways control tables provide color-coded control status, e.g.:
![image](https://user-images.githubusercontent.com/5713754/68633830-56390c80-04c1-11ea-8b5d-adef553503b7.png)

(from http://atopathways.redhatgov.io/product-documents/ansible-tower/nist-800-53/ac/)

However, OCDB does not:
![image](https://user-images.githubusercontent.com/5713754/68633837-618c3800-04c1-11ea-9177-0cfe1fbd7659.png)

Can OCDB be updated to provide similar color coding?

**Comment by isimluk** [comment]
Fixed.


![scrot](https://user-images.githubusercontent.com/6666052/69338750-bbc49000-0c5b-11ea-8a11-5e885cf8eb5f.jpg)

30afe709ba9b17e88b215cb7c8bc1e34a1158f5b
