### ISSUE TITLE
update container repo location

### ISSUE THREAD

**Issue by carlosmmatos** [RedHatGov/ocdb#68]
Currently points to Simon's quay repo. May want to create a public shared repo to use or some other shared method

**Comment by isimluk** [comment]
:+1: 

It only takes to create your own repo (or even organization and then repo) at your favourite container registry (like https://quay.io/ ) and point the new repo to https://github.com/RedHatGov/ocdb

Once the application builds properly it can be deployed from new location, i.e. deployment in openshift is using image stream that needs to be changed to point to the new location.

**Comment by carlosmmatos** [comment]
Roger that!

**Comment by carlosmmatos** [comment]
This is done
