### ISSUE TITLE
Look into 922 controls

### ISSUE THREAD

**Issue by carlosmmatos** [RedHatGov/ocdb#87]
Is there a limit parsing controls? or is this the actual accurate amount. It's strange to see multiple products with the same amount of controls - just need to verify this is correct.

**Comment by isimluk** [comment]
That's the number of items in the NIST-800-53 Revision 4. This number will change after https://github.com/opencontrol/standards/pull/16 is merged.

**Comment by carlosmmatos** [comment]
@isimluk ok I just wanted to make sure that was correct and not a bug.
