### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by trevorbryant** [RedHatGov/ocdb#90]
Building the [Dockerfile](https://github.com/RedHatGov/ocdb/blob/master/Dockerfile#L17) fails with the below output. It says that [react-tokens-4.9.6.tgz](https://registry.yarnpkg.com/@patternfly/react-tokens/-/react-tokens-4.9.6.tgz) doesn't exist when you can independently verify that it does exist.

```bash
$ podman build -t ocdb .
...
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@patternfly/react-tokens/-/react-tokens-4.9.6.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/go/src/github.com/RedHatGov/ocdb/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
STEP 11: FROM registry.centos.org/centos:8
Error: error building at STEP "RUN yarn install --no-progress": error while running runtime: exit status 1
```

I don't know enough about the software chosen to troubleshoot, so dropping an issue here.

**Comment by carlosmmatos** [comment]
@trevorbryant Looking into this now, just ran a clean build using docker on my mac. Going to try this on my fedora desktop with podman just to rule out any potential podman issues.

**Comment by trevorbryant** [comment]
I didn't think to include the working environment. Here is mine:
```bash
$ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
```

**Comment by carlosmmatos** [comment]
I ran everything yesterday fine on my fedora desktop with podman successfully as well.. not sure why you hit those issues although they seem to be somewhat network related.. Quay is a good spot to have it build your image for you, and then you simply run it: `podman run -it -p "3000:3000" quay.io/<yourrepo>/<ocdb|whatever tag you named it>`

**Comment by trevorbryant** [comment]
I haven't taken the time to get back to this, so I'm going to close the issue for now.

I'll open it back up in the future when I get back ton it.
